name: StampedCash
main: naftoreiclag.stampedcash.StampedCashPlugin
version: 1.1.0
author: Naftoreiclag
commands:
    sc:
        description: Stamped Cash main command.
        usage: /<command> <subcommand>
        aliases: [stampedcash, cash, stamp]
    sc mint:
        description: Mint out some new money the proper way.
        usage: /<command> <amount> [quantity]
        aliases: [spawn, create, m]
        permission: stampedcash.mint
    sc combine:
        description: Combines cash in your inventory into one piece of specified size.
        usage: /<command> [amount]
        aliases: [condense, merge, c]
        permission: stampedcash.combine
    sc split:
        description: Break off a wad of specified size from the wad held in your hand.
        usage: /<command> [amount]
        aliases: [break, change, s]
        permission: stampedcash.split
permissions:
    stampedcash.*:
        description: Grants power to all things money.
        children:
            stampedcash.mint: true
            stampedcash.combine: true
            stampedcash.split: true
    stampedcash.mint:
        description: Allows you to print money.
    stampedcash.combine:
        description: Allows you to pile your money together.
    stampedcash.split:
        description: Allows you to divy up your funds.
